### ISSUE TITLE
frequency limit rule question

### ISSUE THREAD

**Issue by kissdish** [Uniswap/uniswap-v3-sdk#122]
_get_token_eth_output_price trigger HttpError 429 too many request for url.  what is the frequency limit rule for the api.

**Comment by marktoda** [comment]
Ah, are you working with this? https://github.com/uniswap-python/uniswap-python/blob/29b3e7226327dca5cd28c1f79c51f0ff5c458e9b/uniswap/uniswap.py#L221 -- this is an unofficial library, please bring your question to them
