### ISSUE TITLE
V2 Methods on V3 SDK

### ISSUE THREAD

**Issue by joaolnpr** [Uniswap/uniswap-v3-sdk#27]
Hello Uniswap Team!

I would like to request the following methods on the new SDK to mirror V2 methods:

- Router
--swapExactTokensForETH
-- swapExactETHForTokens
-- approve

- Factory
--PairCreated

**Comment by moodysalem** [comment]
The V2 SDK only has `Router#swapCallParameters`, and no approve, and it works pretty much the same way as the SwapRouter in V3 SDK which is actually more fully featured
