### ISSUE TITLE
When v3-sdk will ready to use?

### ISSUE THREAD

**Issue by buckyass1** [Uniswap/uniswap-v3-sdk#32]
Hi @moodysalem! I was wondering when will this sdk be ready? Should i use it in my dapp or not right now?  Keep up the good work, thanks.

**Comment by moodysalem** [comment]
I updated the README to indicate the state. It is 'ready' to use in that it works for the Uniswap Interface, but it still receiving the occasional refactor or bugfix. We will deprecate older package versions for bug fixes.
