### ISSUE TITLE
How to I get price?

### ISSUE THREAD

**Issue by risingsun007** [Uniswap/uniswap-v3-sdk#40]
How do I get the price of Token in a pool in V3 in JavaScript with web3?
Do I need to have the address of the UniswapV3Pool and what is address of the UniswapV3Pool?

**Comment by webcaetano** [comment]
Also the `README.md` say : 
```
In-depth documentation on this SDK is available at uniswap.org.
```

This is not true.

There's no docs about v3-sdk . The SDK link there throws to this github 
https://docs.uniswap.org/

**Comment by risingsun007** [comment]
I found a solution in JavaScript with web3.

const bigInt_2 = require('big-integer');
const Web3 = require('web3');

var factoryV3 = new web3.eth.Contract(V3_factory_ABI.factory, factoryV3_address);
var pool_address = await factoryV3.methods.getPool(dai_address,WETH_address,3000).call();
var pool_1 = new web3.eth.Contract(V3_pool_ABI, pool_address);
var pool_balance = await pool_1.methods.slot0.call().call();
sqrtPriceX96 = pool_balance[0];

var number_1 = bigInt_2(sqrtPriceX96)* bigInt_2(sqrtPriceX96) /bigInt_2(2).pow(BigInt(192));
var WTH_price_in_dia = 1/number_1;

**Comment by playniuniu** [comment]
@risingsun007 

Hello  Could you please tell me how to find digits_token_0 and digits_token_1 in contract?

Thanks so much

**Comment by hebeillc** [comment]
Hello, is there any function in v3 like getReserves() of v2?
thanks

**Comment by risingsun007** [comment]
> @risingsun007
> 
> Hello Could you please tell me how to find digits_token_0 and digits_token_1 in contract?
> 
> Thanks so much

You can look up the number of decimals in in a token smart contract on etherscan.io
For example, WETH has 18 decimals, USDT has 6 and USDC has 6.

**Comment by playniuniu** [comment]
@risingsun007 

Thanks so much

**Comment by next2sundeep** [comment]
Any idea how to get tick for entered price ?
Also how to convert entered price to sqrtRatio

**Comment by CorpulentBrony** [comment]
> var number_1 =JSBI.BigInt(sqrtPriceX96 *sqrtPriceX96* (1e(decimals_token_0))/(1e(decimals_token_1))/JSBI.BigInt(2) ** (JSBI.BigInt(192));

You're missing a `)` somewhere and I can't figure out where.

**Comment by quyetdong** [comment]
> I found a solution in JavaScript with web3.
> 
> const JSBI = require('jsbi'); const Web3 = require('web3');
> 
> var factoryV3 = new web3.eth.Contract(V3_factory_ABI.factory, factoryV3_address); var pool_address = await factoryV3.methods.getPool(dai_address,WETH_address,3000).call(); var pool_1 = new web3.eth.Contract(V3_pool_ABI, pool_address); var pool_balance = await pool_1.methods.slot0.call().call(); varsqrtPriceX96 = pool_balance[0];
> 
> var number_1 =JSBI.BigInt(sqrtPriceX96 *sqrtPriceX96* (1e(decimals_token_0))/(1e(decimals_token_1))/JSBI.BigInt(2) ** (JSBI.BigInt(192));

this is helpful, thank you very much.

**Comment by mytokendemo** [comment]
Hello, thank you very much for your sharing, I would like to ask uniswapV3 to get the contract address of all the tokens in the pool through web3? There are allpairs in V2 but not in V3, what should I do?

**Comment by bitfede** [comment]
why was 3000 picked as the `fee` value for `getPool` ? Thanks for clarifying this

**Comment by risingsun007** [comment]
3000 is the .3% pool.   A pool with a .05% fee level would correspond to 500.    Each pool in uniswapv3 has a fee level associated with it

**Comment by mytokendemo** [comment]
@risingsun007   Hello, I would like to ask uniswapV3 to get the contract address of all the tokens in the pool through web3? There are allpairs in V2 but not in V3, what should I do?

**Comment by risingsun007** [comment]
V3 doesn't have that functionality.

**Comment by mytokendemo** [comment]
@risingsun007   Thank you very much for your reply, I want to know if there is any other way to get it besides web3, I will use python

**Comment by playniuniu** [comment]
@mytokendemo you may check the uniswap v3 graphql api, like [this](https://docs.uniswap.org/sdk/subgraph/subgraph-examples#all-tokens)

**Comment by mytokendemo** [comment]
@playniuniu  There is a limit to graphQl, I can only get 1000, I want to get the contract addresses of all the pools in v3, what should I do

**Comment by davidaucoin7377** [comment]
You want me on this phone or you want me to get on the computer the computer had the Java problem we can fix it though

**Comment by davidaucoin7377** [comment]
I'm logging in on my other computer

**Comment by anniejulia** [comment]
var number_1 =JSBI.BigInt(sqrtPriceX96 sqrtPriceX96 (1e(decimals_token_0))/(1e(decimals_token_1))/JSBI.BigInt(2) ** (JSBI.BigInt(192));  this is wrong!  Precision calculation is error.
var number_1 =JSBI.BigInt(sqrtPriceX96 * (1e(decimals_token_0))/(1e(decimals_token_1)) ** 2 / JSBI.BigInt(2) ** (JSBI.BigInt(192)); 
This is True！

**Comment by IshitaSrivast** [comment]
I wanted to run multicalls for the same. Is there a way?
