### ISSUE TITLE
How to use SDK for getAmountOut?

### ISSUE THREAD

**Issue by boy-good** [Uniswap/uniswap-v3-sdk#48]
![image](https://user-images.githubusercontent.com/39320533/124094016-f377f880-da8a-11eb-8951-6b6c1171c5e2.png)
And than i use poolExample.getOutputAmount(inputAmount) but its always 1ETH trade 1000000USDT...
so how init ticks?Please help

**Comment by willhennessy** [comment]
Hi boy-good, I'm sorry this type of question is best directed to the developer channel in our discord. Cheers!
