### ISSUE TITLE
How to get an amount of both tokens of my position? Uni V3

### ISSUE THREAD

**Issue by trydex** [Uniswap/uniswap-v3-sdk#49]
Hi!

Is there a way to get amount of both tokens of my position in a pool (Uni v3 )? I found method "positions" of [NonfungiblePositionManager](https://docs.uniswap.org/reference/periphery/NonfungiblePositionManager) but it returns something weird and the result doesn't look like my position:

```
const positionManager = require('@uniswap/v3-periphery/artifacts/contracts/NonfungiblePositionManager.sol/NonfungiblePositionManager.json');
var contractAddress = "0xc36442b4a4522e871399cd717abdd847ab11fe88";
var contract = new web3.eth.Contract(positionManager.abi, contractAddress);
var tokenId = 77777; //my tokenId
contract.methods.positions(tokenId).call().then(function(result){
  console.log(result);
});
```

Result:
![image](https://user-images.githubusercontent.com/20781342/124396589-246a5e80-dd13-11eb-83b1-efcbf95ee599.png)

**Comment by peggy001** [comment]
how  to get the amounts of both token of the nft in uniswapV3?
and the tokenOwed0 is in unit128,how to convert into the normal unit?...

**Comment by peggy001** [comment]
could u share the method plz?? the way to get amount of both tokens of my position in a pool (Uni v3 :)
