### ISSUE TITLE
Price impact for multi-route trades

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/uniswap-v3-sdk#54]
Refactor computePriceImpact to support multiple routes

Definition:
https://github.com/Uniswap/uniswap-sdk-core/blob/fd37337823fef05d4f530c4334eec63d7945ec19/src/utils/computePriceImpact.ts

Usage:
https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/entities/trade.ts#L116

**Comment by willpote** [comment]
https://github.com/Uniswap/uniswap-v3-sdk/pull/55
