### ISSUE TITLE
getOutputAmount - didn't match expected result

### ISSUE THREAD

**Issue by bezrazli4n0** [Uniswap/uniswap-v3-sdk#70]
Hello, i'm trying to obtain output amount for specific pair, but result didn't match expected, what am I doing wrong?.
![image](https://user-images.githubusercontent.com/56516965/128843188-791ee6ca-befd-4863-afa1-b3f6af6fa336.png)

**Comment by sydneyhenrard** [comment]
Try using
INPUT_AMOUNT = JSBI.exponentiate(JSBI.BigInt(10), JSBI.BigInt(18))
